### ISSUE TITLE
`OrbitControls.svelte` possible typo reported on the Discord in #gl by @vdvman1

### ISSUE THREAD

**Issue by delhanty** [Rich-Harris/svelte-cubed#12]
`OrbitControls.svelte` possible typo reported on the Discord in #gl by @vdvman1

> Was reading through the svelte-cubed source just out of curiosity, and came across this in src/lib/components/controls/OrbitControls.svelte:
controls.target.x !== target[0] ||
controls.target.x !== target[1] ||
controls.target.x !== target[2]
>
>That should probably be x, y, and z, rather than x, x, x 
>I don't really have the time to submit a proper issue or pull request right now though, so just quickly sharing it here in case someone else has time, and to possibly remind myself to do so later
>
>Appears twice in that file
>Looks like a simple copy-paste error

[https://discord.com/channels/457912077277855764/678020543286476820/912572603766542347](https://discord.com/channels/457912077277855764/678020543286476820/912572603766542347)

1st instance appears starting on line 62.

2nd instance appears starting on line 85. 

<https://github.com/Rich-Harris/svelte-cubed/blob/main/src/lib/components/controls/OrbitControls.svelte>

**Comment by Rich-Harris** [comment]
thank you! fixed in 0.2.1
