### ISSUE TITLE
Add PointerLockControls

### ISSUE THREAD

**Issue by Myrmod** [Rich-Harris/svelte-cubed#36]
Hello, 

I am trying to add `PointerLockControls`, but somehow they're not working:

https://github.com/Myrmod/svelte-cubed/blob/main/src/lib/components/controls/PointerLockControls.svelte

What I want to be able to do is essentially [this](https://threejs.org/examples/?q=pointerloc#misc_controls_pointerlock), the corresponding code can be found [here](https://github.com/mrdoob/three.js/blob/master/examples/misc_controls_pointerlock.html)

For the movement via `KeyBoardEvent` I am not sure if it's best to add them directly into the `PointerLockControls` or inside of another function/component. If I get this to work I would like to open up a pull request. :)

Any suggestions?

**Comment by DefinitelyMaybe** [comment]
I've done a similar thing before if you'd like to have a quick look over [that source](https://github.com/DefinitelyMaybe/glowing-octo-train/blob/ea39d347036c08680850a89cd05625aa7eddddea/src/routes/simonsWorld.svelte#L56).

Something else that might be helpful is [this video](https://www.youtube.com/watch?v=3_D-3HPUdEI) about finite state machines but that depends on where your going with your work.

Another suggestion would be the good old `console.log()`ing a bunch of things or add eventlisteners to try and pin point what might not be working

**Comment by Myrmod** [comment]
Thank you for the hint. I created a basic implementation of the afforementioned controls and set up a pull request. The movement feature will be a separate issue I think, because not everyone needs it, if they're using the `PointerLockControls`. For something like a rollercoaster it would be not required.

 :)
